version: '3.5'
services:
  web:
    tty: true
    restart: always
    stdin_open: true
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/mock-api
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
