# Generated by Django 3.2.5 on 2021-07-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_string', models.CharField(max_length=300)),
                ('http_method', models.CharField(choices=[('post', 'POST'), ('post', 'PUT'), ('post', 'GET'), ('post', 'PATCH')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MockResponse',
            fields=[
                ('body', models.JSONField()),
                ('status', models.IntegerField()),
                ('http_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.path')),
            ],
        ),
    ]
