# Generated by Django 3.2.5 on 2021-07-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_http_method_mockresponse_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='http_method',
            field=models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('GET', 'GET'), ('PATCH', 'PATCH')], max_length=5),
        ),
    ]
