# Generated by Django 3.2.5 on 2021-07-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_path_http_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='body_schema',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
